<?php

namespace App\SharedFeatures\DTOs;

final class User
{
    public function __construct(
        public readonly string  $id,
        public readonly string  $name,
        public readonly string  $lastname,
        public readonly string  $username,
        public readonly string  $fullName,
        public readonly string  $email,
        public readonly ?string $phone,
        public readonly ?string $sex,
        public readonly ?string $birth,
        public readonly ?string $referer,
        public readonly ?string $iblinkId,
        public readonly ?string $ibratio,
        public readonly ?string $discountref,
        public readonly string  $countryIso,
        public readonly ?string $address,
        public readonly ?string $state,
        public readonly ?string $city,
        public readonly ?string $street,
        public readonly ?string $zipcode,
        public readonly ?int    $langsId,
        // public readonly ?string $codeResetPassword,
        // public readonly ?string $emailVerifiedAt,
        // public readonly ?string $phoneVerifiedAt,
        // public readonly ?string $img,
        public readonly int     $status,
        // public readonly int     $online,
        public readonly string  $client,
        // public readonly string  $lastlogin,
        // public readonly int     $acceptMarketingEmail,
        // public readonly ?string $unsuscribeCode,
        // public readonly ?string $accessUnderMaintain,
        public readonly string  $clientType,
        // public readonly string  $theme,
        public readonly array   $security2fa,
        public readonly array   $roles,
        // public readonly string  $createdAt,
        // public readonly string  $updatedAt,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            name: $data['name'],
            lastname: $data['lastname'],
            username: $data['username'],
            fullName: $data['full_name'],
            email: $data['email'],
            phone: $data['phone'],
            sex: $data['sex'],
            birth: $data['birth'],
            referer: $data['referer'],
            iblinkId: $data['iblink_id'],
            ibratio: $data['ibratio'],
            discountref: $data['discountref'],
            countryIso: $data['country_iso'],
            address: $data['address'],
            state: $data['state'],
            city: $data['city'],
            street: $data['street'],
            zipcode: $data['zipcode'],
            langsId: $data['langs_id'],
            // codeResetPassword: $data['code_reset_password'],
            // emailVerifiedAt: $data['email_verified_at'],
            // phoneVerifiedAt: $data['phone_verified_at'],
            // img: $data['img'],
            status: $data['status'],
            // online: $data['online'],
            client: $data['client'],
            // lastlogin: $data['lastlogin'],
            // acceptMarketingEmail: $data['accept_marketing_email'],
            // unsuscribeCode: $data['unsuscribe_code'],
            // accessUnderMaintain: $data['access_under_maintain'],
            clientType: $data['client_type'],
            // theme: $data['theme'],
            security2fa: $data['security2fa'],
            roles: $data['roles'],
            // createdAt: $data['created_at'],
            // updatedAt: $data['updated_at'],
        );
   
    }
}